### ISSUE TITLE
Add privacy option?

### ISSUE THREAD

**Issue by maelle** [jimhester/tidyversedashboard#6]
Not sure if generally useful. I used that for [Locke Data](https://github.com/lockedata/tidyversedashboard). Privacy could be "all" (default like now), "private", "public" to query only private/public repos.

Technically it'd mean changing [this query](https://github.com/lockedata/tidyversedashboard/blob/master/inst/repo_summary.graphql) by adding privacy e.g. `repositories(first:20, affiliations: OWNER, orderBy: {field: PUSHED_AT, direction: DESC}, privacy: PUBLIC, isFork: false, after: $cursor)` but it couldn't be parameterized for having all repos: the privacy only accept either PUBLIC or PRIVATE, so there should be some sort of gluing I guess if the privacy isn't "all".

**Comment by jimhester** [comment]
Alternatively this could be controlled by the permissions you give the personal access token you are using, I am inclined to go that route rather than adding an additional parameter.

But maybe we should return the privacy status of the repo in the table?

Also NB, if you just don't assign the parameter it is not used, so no need to do upstream glueing.

**Comment by maelle** [comment]
Not sure I follow, would you change your environment variable depending on what you're doing?

Sounds good to return the privacy status!

Good to know about the parameter!

**Comment by jimhester** [comment]
You were right, this is a good idea, it is now added!

**Comment by maelle** [comment]
:joy: I might be happier to have been right than to see it added 🙈 Thanks!
